server:
  port: 9090

spring:
  application:
    name: text-to-speech-service
  web:
    resources:
      add-mappings: false

azure:
  speech:
    key: dummy key
    region: eastus
    voice: en-US-JennyNeural
    output-format: Audio16Khz32KBitRateMonoMp3

logging:
  level:
    root: INFO
    com.jarvis.texttospeech: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics